### ISSUE TITLE
3. Online version

### ISSUE THREAD

**Issue by vsoch** [gasparl/citapp_pc#3]
You reference an "online version" on osf, but this isn't easy enough to use or interact
with. I'd recommend you deploy the static files to Github pages for a preview
that lives with (and thus is versioned with) the codebase. I would recommend having
the demo in a "docs" folder on the master branch so you don't need to worry about updating
a separate branch (gh-pages). If you need any help / have questions please ask and I will
help you!

Review: https://github.com/openjournals/joss-reviews/issues/1179

**Comment by gasparl** [comment]
Brilliant, I didn't know it's so easy to host my page on Github - thank you for the suggestion! 
I'm not sure though what you mean by "having
the demo in a "docs" folder". The application is now simply acceptable via https://gasparl.github.io/citapp_pc/CITapp.html
I would just leave it like that and refer to this in the repository and in the paper.

**Comment by vsoch** [comment]
For the demo, it might be helpful to add hints / pre-filled in values for the content on the right (I don't know what to put) and most that are previewing likely won't have read through any documentation yet.

![image](https://user-images.githubusercontent.com/814322/51259240-bb8fa000-1979-11e9-9c16-c2781abc186e.png)

This would be the kind of reason to have the demo separate from the thing you are giving to users to deploy - the demo would have more learning tips / pre-filled in boxes for teaching.

**Comment by gasparl** [comment]
I added a demo possibility that can automatically fill these example using a button, but, for compactness, I simply added it as a new menu in the main application:
![image](https://user-images.githubusercontent.com/37374850/51437582-88624f00-1ca0-11e9-9575-bea083cdf1d8.png)

So now it's available via the same page; https://gasparl.github.io/citapp_pc/CITapp.html. I added this link both to the paper and the README.

**Comment by vsoch** [comment]
This is totally awesome! I both love it and can say you went above my expectation to make it easier to learn how to use. This definitely closes this issue. Great work!
