### ISSUE TITLE
7. "Installation" or Usage Instructions

### ISSUE THREAD

**Issue by vsoch** [gasparl/citapp_pc#7]
The installation, based on the README, is to "drag and drop the file in a browser."
As a stupid Github user I could try grabbing the link to the file and dropping it in a new 
tab, and this obviously wouldn't work! I would suggest a more direct instruction that
can first direct the user to a static url to preview the experiment, and then
if the user wants to deploy  on his / her own, provide complete instructions to:

 1. Fork the repository to their Github account 
 2. Clone the forked repository
 3. Customize (in some way) if necessary?
 4. Either put on a local web server, or give instructions to deploy to Github pages.

Also, you could provide the user with a Dockerized version, which would let them
run a Docker container bound to port 80 to run it immediately without needing to do
cloning, etc. This would also be reproducible because you would have all versions
of the software build into containers. let me know if you need help with this, glad
to help with creating a Dockerfile and building the container with some CI (e.g., circleci)
and pushing the container to Docker Hub.

Review: https://github.com/openjournals/joss-reviews/issues/1179

**Comment by gasparl** [comment]
I added more precise instructions about how the application may be used.

I'm not sure though about the Dockerized version. I am completely new to this, but if I understand correctly the only advantage would be that separate versions are kept unchanged in these containers. But then downloading or cloning could do just the same, and these can be done extremely easily, literally with a few button clicks. (The huge green "Clone or download" button for the repository.)
But if I misunderstand and there is more to this and/or you really think it would be relevant, then I would indeed appreciate it you helped out with the implementation :)

**Comment by gasparl** [comment]
I see. 
It's really nice of you to offer. Still, it doesn't seem pressing, so I would like to ask you to let me off the hook for now. If someone does ask for it and/or this test will actually become frequently used (as I would wish), I will not hesitate to get back to you about this.

**Comment by vsoch** [comment]
Sounds good! You're off the hook! :) Closing issue.

**Comment by gasparl** [comment]
Thanks :)
